# EDCOP Packetbeat Chart values
images:
  packetbeat: docker.elastic.co/beats/packetbeat:6.2.4
  logstash: docker.elastic.co/logstash/logstash:6.2.4 
  redis: redis:4.0.9
networks:
  # Overlay is the name of the default cni network
  overlay: calico
  # Passive is the name of the sriov interface
  passive: passive
nodeSelector:
  nodetype: worker
packetbeatConfig:
  # Requests are set to accommodate resource limited VMs
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 2
    memory: 4G
logstashConfig:
  threads: 2 
  batchCount: 250
  initialJvmHeap: 4g
  maxJvmHeap: 4g
  pipelineOutputWorkers: 2 
  pipelineBatchSize: 150  
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 2
    memory: 8G
redisConfig:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 2
    memory: 8G
